### ISSUE TITLE
Django 1.9 crash:

### ISSUE THREAD

**Issue by dbykadorov** [syrusakbary/pyjade#229]
After upgrading Django to 1.9 I got following error:

```
  File ".env\lib\site-packages\pyjade\ext\django\__init__.py", line 2, in <module>
    from .compiler import Compiler
  File ".env\lib\site-packages\pyjade\ext\django\compiler.py", line 65, in <module>
    from django.template import add_to_builtins
ImportError: cannot import name add_to_builtins
```

Looks like this issue caused by changes in django builtins: https://docs.djangoproject.com/en/dev/releases/1.9/#django-template-base-add-to-builtins-is-removed

**Comment by blx** [comment]
Hi,

This is also in #221, where the solution was to install from the github master branch instead of PyPI -- maybe try that?

**Comment by dbykadorov** [comment]
@blx looks like you're right:

in master https://github.com/syrusakbary/pyjade/blob/master/pyjade/ext/django/compiler.py#L62

```python
try:
    try:
        from django.template.base import add_to_builtins
    except ImportError: # Django < 1.8
        from django.template import add_to_builtins
    add_to_builtins('pyjade.ext.django.templatetags')
except ImportError:
    # Django 1.9 removed add_to_builtins and instead
    # provides a setting to specify builtins:
    # TEMPLATES['OPTIONS']['builtins'] = ['pyjade.ext.django.templatetags']
    pass
```

I need to install pyjade from master and add 'builtins' option:

`TEMPLATES['OPTIONS']['builtins'] = ['pyjade.ext.django.templatetags']`

**Comment by arnists** [comment]
Please bump PyPI version?

**Comment by syrusakbary** [comment]
Will upload a new version to PyPI soon :)
